#!/bin/bash
#SBATCH --partition=DGX
#SBATCH --account=lade
#SBATCH --nodes=1
#SBATCH --time=6:00:00            
#SBATCH --ntasks-per-node=1       
#SBATCH --cpus-per-task=32           
#SBATCH --mem=80G                
#SBATCH --job-name=test
#SBATCH --gres=gpu:1 

#source /etc/profile.d/modules.sh
#module use /opt/nvidia/hpc_sdk/modulefiles/
#module load nvhpc
source /u/area/ddoimo/anaconda3/bin/activate ./env_amd_new

export OMP_NUM_THREADS=32
export PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True" 

MODEL_SIZE=7B
NUM_GPUS=1
TOTAL_BATCH_SIZE=16
BATCH_SIZE_PER_GPU=1
GRADIENT_ACC_STEPS=$(($TOTAL_BATCH_SIZE/$NUM_GPUS/$BATCH_SIZE_PER_GPU))
model_name='llama-2-7b'


# Lora training
#torchrun --rdzv-backend=c10d --rdzv-endpoint=localhost:0 \
#        	--nnodes=1  --nproc-per-node=1 \
accelerate launch \
    --mixed_precision bf16 \
    --num_machines 1 \
    --num_processes $NUM_GPUS \
    --dynamo_backend 'no' \
   open_instruct/overlap_finetunes.py \
    --model_name_or_path  /orfeo/cephfs/scratch/area/ddoimo/llama/llama_v2/models_hf/$model_name \
    --use_lora \
    --lora_rank 64 \
    --lora_alpha 16 \
    --lora_dropout 0.1 \
    --tokenizer_name /orfeo/cephfs/scratch/area/ddoimo/llama/llama_v2/models_hf/$model_name \
    --use_slow_tokenizer \
    --val_file /orfeo/cephfs/scratch/area/ddoimo/data/open_instruct/eval/mmlu \
    --test_file /orfeo/cephfs/scratch/area/ddoimo/data/open_instruct/eval/mmlu \
    --max_seq_length 1024 \
    --batch_size $TOTAL_BATCH_SIZE \
    --preprocessing_num_workers 16 \
    --checkpointing_steps epoch \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --measure_baselines \
    --overlap_base_dir "/u/area/ddoimo/ddoimo/open/geometric_lens/repo/results/validation/$model_name" \
    --ckpt_dir "/u/area/ddoimo/ddoimo/finetuning_llm/open-instruct/results/$model_name/epoch_0" \
    --output_dir ./results/${model_name}/ \
    --out_filename "" \

