#!/bin/bash
#SBATCH --partition=DGX
#SBATCH --account=lade
#SBATCH --nodes=1
#SBATCH --time=6:00:00            
#SBATCH --ntasks-per-node=1       
#SBATCH --cpus-per-task=32           
#SBATCH --mem=100G                
#SBATCH --job-name=test
#SBATCH --gres=gpu:1 

source /etc/profile.d/modules.sh
module use /opt/nvidia/hpc_sdk/modulefiles/
module load nvhpc
source /u/area/ddoimo/anaconda3/bin/activate ./env_amd

#conda activate ./env_amd
export OMP_NUM_THREADS=32

#export CUDA_VISIBLE_DEVICES=0,1,2,3

MODEL_SIZE=7B
NUM_GPUS=1
TOTAL_BATCH_SIZE=3
BATCH_SIZE_PER_GPU=1
GRADIENT_ACC_STEPS=$(($TOTAL_BATCH_SIZE/$NUM_GPUS/$BATCH_SIZE_PER_GPU))
#echo "Training llama model ${MODEL_SIZE} using $NUM_GPUS GPUs, $BATCH_SIZE_PER_GPU batch size per GPU, $GRADIENT_ACC_STEPS gradient accumulation steps"

# Lora training
accelerate launch \
    --mixed_precision bf16 \
    --num_machines 1 \
    --num_processes $NUM_GPUS \
    open_instruct/finetune.py \
    --model_name_or_path  /orfeo/cephfs/scratch/area/ddoimo/llama/llama_v1/models_hf/7B \
    --use_lora \
    --lora_rank 64 \
    --lora_alpha 16 \
    --lora_dropout 0.1 \
    --tokenizer_name /orfeo/cephfs/scratch/area/ddoimo/llama/llama_v1/models_hf/7B \
    --use_slow_tokenizer \
    --train_file /orfeo/cephfs/scratch/area/ddoimo/open-instruct/data/processed/dolly/dolly_data.jsonl \
    --val_file /orfeo/cephfs/scratch/area/ddoimo/open-instruct/data/eval/mmlu \
    --test_file /orfeo/cephfs/scratch/area/ddoimo/open-instruct/data/eval/mmlu \
    --max_seq_length 1024 \
    --preprocessing_num_workers 16 \
    --checkpointing_steps epoch \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps $GRADIENT_ACC_STEPS \
    --learning_rate 1e-4 \
    --lr_scheduler_type linear \
    --warmup_ratio 0.03 \
    --weight_decay 0. \
    --num_train_epochs 2 \
    --output_dir ./results/${MODEL_SIZE}_lora/ \
    --with_tracking \
    --report_to tensorboard \
    --logging_steps 20 \
    --eval_steps 50
    #--eval_steps 50 &&

#python open_instruct/merge_lora.py \
#    --base_model_name_or_path ../hf_llama2_models/${MODEL_SIZE} \
#    #--lora_model_name_or_path $RESULTS_FOLDER \
#    --lora_name_or_path ./results/${MODEL_SIZE}_lora/ \
#    --output_dir ./results/${MODEL_SIZE}_lora_merged/ \
#    --save_tokenizer
#--use_deepspeed \
#--deepspeed_config_file ds_configs/stage3_no_offloading_accelerate.conf \
#--use_flash_attn \
