#!/bin/bash
#SBATCH --partition=DGX
#SBATCH --account=lade
#SBATCH --nodes=1
#SBATCH --time=4:00:00            
#SBATCH --ntasks-per-node=1       
#SBATCH --cpus-per-task=32           
#SBATCH --mem=400G  #it is intended per node          
#SBATCH --job-name=test
#SBATCH --gres=gpu:2 #it is intended per node

source /u/area/ddoimo/anaconda3/bin/activate ./env_amd_new

export OMP_NUM_THREADS=32
export PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True" 

NUM_GPUS=1
TOTAL_BATCH_SIZE=24
BATCH_SIZE_PER_GPU=1
GRADIENT_ACC_STEPS=$(($TOTAL_BATCH_SIZE/$NUM_GPUS/$BATCH_SIZE_PER_GPU))

model_name="llama-3-8b"
folder="llama_v3"

#model_name="mistral-1-7b"
#folder="mistral_v1"

nodes=( $( scontrol show hostnames $SLURM_JOB_NODELIST ) )
nodes_array=($nodes)
head_node=${nodes_array[0]}
head_node_ip=$(srun --nodes=1 --ntasks=1 -w "$head_node" hostname --ip-address)

srun torchrun \
    --nnodes=$SLURM_NTASKS \
    --node-rank=$SLURM_NODEID \
    --nproc-per-node=2 \
    --rdzv-id=$SLURM_PROCID \
    --rdzv-backend=c10d \
    --rdzv-endpoint=$head_node:29400 \
   open_instruct/finetune_fsdp_multinode.py \
    --model_name_or_path  /orfeo/cephfs/scratch/area/ddoimo/models/$folder/models_hf/$model_name \
    --use_lora \
    --lora_rank 64 \
    --lora_alpha 16 \
    --lora_dropout 0.1 \
    --tokenizer_name /orfeo/cephfs/scratch/area/ddoimo/models/$folder/models_hf/$model_name \
    --use_slow_tokenizer \
    --low_cpu_mem_usage \
    --train_file /orfeo/cephfs/scratch/area/ddoimo/data/open_instruct/processed/dolly/dolly_data.jsonl \
    --val_file /orfeo/cephfs/scratch/area/ddoimo/data/open_instruct/eval/mmlu \
    --test_file /orfeo/cephfs/scratch/area/ddoimo/data/open_instruct/eval/mmlu \
    --max_seq_length 2048 \
    --batch_size $TOTAL_BATCH_SIZE \
    --preprocessing_num_workers 16 \
    --checkpointing_steps epoch \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --batch_size $TOTAL_BATCH_SIZE \
    --learning_rate 2e-4 \
    --lr_scheduler_type cosine \
    --warmup_ratio 0.05 \
    --weight_decay 0. \
    --num_train_epochs 4 \
    --output_dir "./results/fsdp_test/${model_name}/" \
    --measure_baselines \
    --overlap_base_dir "/u/area/ddoimo/ddoimo/open/geometric_lens/repo/results/validation/$model_name" \
    --samples_per_subject 20 \
    --out_filename ""  \
    --activation_checkpointing
    #--train_on_test \
    #--mask_path "/u/area/ddoimo/ddoimo/finetuning_llm/open-instruct/open_instruct/my_utils/test_mask_100.npy"   \
#--learning_rate 1e-4 \
    #--with_tracking \
    #--report_to tensorboard \
