#!/bin/bash
#SBATCH --partition=DGX
#SBATCH --account=lade
#SBATCH --nodes=1
#SBATCH --time=6:00:00            
#SBATCH --ntasks-per-node=1       
#SBATCH --cpus-per-task=32           
#SBATCH --mem=80G                
#SBATCH --job-name=test
#SBATCH --gres=gpu:1 

#source /etc/profile.d/modules.sh
#module use /opt/nvidia/hpc_sdk/modulefiles/
#module load nvhpc
source /u/area/ddoimo/anaconda3/bin/activate ./env_amd_new

export OMP_NUM_THREADS=32
export PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True" 

NUM_GPUS=1
TOTAL_BATCH_SIZE=16
BATCH_SIZE_PER_GPU=1
GRADIENT_ACC_STEPS=$(($TOTAL_BATCH_SIZE/$NUM_GPUS/$BATCH_SIZE_PER_GPU))

model_name="llama-3-8b"
folder="llama_v3"

# Lora training
#torchrun --rdzv-backend=c10d --rdzv-endpoint=localhost:0 \
#        	--nnodes=1  --nproc-per-node=1 \
accelerate launch \
    --mixed_precision bf16 \
    --num_machines 1 \
    --num_processes $NUM_GPUS \
    --dynamo_backend 'no' \
   open_instruct/finetune.py \
    --model_name_or_path  /orfeo/cephfs/scratch/area/ddoimo/llama/$folder/models_hf/$model_name \
    --use_lora \
    --lora_rank 64 \
    --lora_alpha 16 \
    --lora_dropout 0.1 \
    --tokenizer_name /orfeo/cephfs/scratch/area/ddoimo/llama/$folder/models_hf/$model_name \
    --use_slow_tokenizer \
    --train_file /orfeo/cephfs/scratch/area/ddoimo/data/open_instruct/processed/dolly/dolly_data.jsonl \
    --val_file /orfeo/cephfs/scratch/area/ddoimo/data/open_instruct/eval/mmlu \
    --test_file /orfeo/cephfs/scratch/area/ddoimo/data/open_instruct/eval/mmlu \
    --max_seq_length 1024 \
    --batch_size $TOTAL_BATCH_SIZE \
    --preprocessing_num_workers 16 \
    --checkpointing_steps epoch \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps $GRADIENT_ACC_STEPS \
    --learning_rate 2e-4 \
    --lr_scheduler_type linear \
    --warmup_ratio 0.03 \
    --weight_decay 0. \
    --num_train_epochs 4 \
    --output_dir ./results/${model_name}/ \
    --logging_steps 20 \
    --eval_steps 20 \
    --measure_baselines \
    --overlap_base_dir "/u/area/ddoimo/ddoimo/open/geometric_lens/repo/results/validation/$model_name" \
    --out_filename "" \
    --train_on_dev
#--learning_rate 1e-4 \
    #--with_tracking \
    #--report_to tensorboard \
